// apps-data.jsx — App metadata + case-study content

const APPS_DATA = [
  {
    id: 'declutr',
    index: '01',
    name: 'Declutr',
    tagline: 'Sweep the cruft from your camera roll.',
    blurb: 'A Tinder-style way to clear out your camera roll. Swipe, delete, watch the gigabytes come back.',
    status: 'shipping',
    statusLabel: 'On the App Store',
    screen: 'ScreenDeclutr',
    tint: 'rgba(244, 114, 182, 0.28)',
    tags: ['iOS 17+', 'SwiftUI', 'SwiftData', 'PhotoKit'],
    year: '2024',
    role: 'Designer & developer',
    stack: ['Swift', 'SwiftUI', 'SwiftData', 'PhotoKit', 'StoreKit 2', 'TipKit'],
    one: 'A photo decluttering app that turns digital cleanup into a thumb-flick game.',
    overview: [
      'Most people\'s photo libraries are a graveyard of accidental selfies, blurry shots and screenshots of receipts. Declutr makes culling feel less like a chore and more like flicking through a deck — one swipe to keep, one to bin.',
      'The app pulls directly from the user\'s Photos library through PhotoKit, queues deletions locally with SwiftData, and only commits them when the user is sure. Storage savings update live as you go.',
    ],
    features: [
      { t: 'Stack-based review', d: 'A swipeable card UI built on SwiftUI gestures, with elastic snap-back and a side-lit hint on dominant direction.' },
      { t: 'Live storage delta', d: 'Computes byte impact per asset as you queue deletions, so you see exactly how much space you\'re reclaiming.' },
      { t: 'Smart batches', d: 'Auto-groups by burst, location, screenshot and similar-looking shots so you breeze through duplicates first.' },
      { t: 'Two-tap undo', d: 'Nothing leaves the system until you confirm at the end of a session — never lose a photo you actually wanted.' },
    ],
    metrics: [
      { v: '4.8★', k: 'App Store rating' },
      { v: '12k', k: 'photos cleared / wk' },
      { v: '2.4 GB', k: 'avg freed / user' },
    ],
  },
  {
    id: 'maptok',
    index: '02',
    name: 'Trackside',
    tagline: 'A flight log for the railways.',
    blurb: 'Track every UK train journey with live rail data. Flighty, but for the railways.',
    status: 'beta',
    statusLabel: 'In TestFlight',
    screen: 'ScreenMapTok',
    tint: 'rgba(125, 211, 252, 0.28)',
    mockups: [
      'assets/mockups/trackside-1.png',
      'assets/mockups/trackside-2.png',
      'assets/mockups/trackside-3.png',
    ],
    tags: ['iOS 17+', 'SwiftUI', 'MapKit', 'Rail Data API'],
    year: '2025',
    role: 'Designer & developer',
    stack: ['Swift', 'SwiftUI', 'MapKit', 'Rail Data Marketplace', 'WidgetKit', 'Live Activities'],
    one: 'A trip-tracking app for UK rail — pivoted from a travel idea, kept the bundle name.',
    overview: [
      'Trackside started as a different product. The pivot kept the bundle id but rebuilt the experience around something I actually wanted: a Flighty for British trains. Live arrivals, platforms, delays and route maps — without the operator app fragmentation.',
      'It pulls real-time data from the Rail Data Marketplace, mirrors it into a Live Activity when you\'re onboard, and keeps a permanent log of every journey you take.',
    ],
    features: [
      { t: 'Live journey timeline', d: 'A vertical stop list with platforms, predicted times and on-the-minute delay deltas, sourced directly from operator feeds.' },
      { t: 'Route on MapKit', d: 'Polylines drawn from real OS data; the train\'s position interpolates smoothly between known signal locations.' },
      { t: 'Lock-screen Live Activity', d: 'A pared-back companion that surfaces the next stop, ETA and platform without unlocking your phone.' },
      { t: 'Trip log', d: 'Distance, operator and on-time stats compound into a year-end recap, like Spotify Wrapped for rail.' },
    ],
    metrics: [
      { v: '420', k: 'TestFlight users' },
      { v: '8k', k: 'journeys logged' },
      { v: '97%', k: 'arrival prediction acc.' },
    ],
  },
  {
    id: 'pub-roulette',
    index: '03',
    name: 'Pub Roulette',
    tagline: 'A pub crawl, but the wheel decides.',
    blurb: 'A multiplayer crawl game with team assignments, randomised orders, photo evidence, and chaos.',
    status: 'shipping',
    statusLabel: 'On the App Store',
    screen: 'ScreenPubRoulette',
    tint: 'rgba(168, 85, 247, 0.32)',
    tags: ['iOS 17+', 'SwiftUI', 'Firebase', 'Mesh Gradients'],
    year: '2024',
    role: 'Designer & developer',
    stack: ['Swift', 'SwiftUI', 'Firebase', 'Realtime Database', 'PhotosUI', 'Symbol Effects'],
    one: 'A real-time multiplayer iOS game that turns a night out into a chaotic group competition.',
    overview: [
      'Pub Roulette dropped out of a "what if the night planned itself?" conversation. Players join a party, get spun into random teams, receive a randomised drink order at each pub, and race to complete the crawl by submitting photo evidence.',
      'It\'s the most visually ambitious app I\'ve shipped — full-screen mesh gradients, custom physics on the wheel spin, symbol effects on every state transition, and a Firebase backend syncing eight players in real-time.',
    ],
    features: [
      { t: 'Animated wheel of fate', d: 'A custom spinner with weighted easing, haptics on each sector and a confetti payoff. Sectors generate party-wide.' },
      { t: 'Photo evidence', d: 'Each pub locks until a team uploads proof — written into Realtime Database and broadcast to every player\'s screen.' },
      { t: 'Mesh gradient theming', d: 'Each party gets a unique colour palette generated from the host\'s name, used across every surface.' },
      { t: 'Live leaderboard', d: 'Scoring rolls in over the night with bonuses for speed, chaos, and the most enthusiastic group photo.' },
    ],
    metrics: [
      { v: '2.1k', k: 'parties hosted' },
      { v: '11k', k: 'drinks ordered' },
      { v: '#3', k: 'UK Party Games chart' },
    ],
  },
  {
    id: 'optidose',
    index: '04',
    name: 'Optidose',
    tagline: 'A calm interface for a complicated regimen.',
    blurb: 'Medication tracking with HealthKit, smart reminders, and a daily ritual that doesn\'t shout at you.',
    status: 'beta',
    statusLabel: 'In TestFlight',
    screen: 'ScreenOptidose',
    tint: 'rgba(134, 239, 172, 0.28)',
    tags: ['iOS 17+', 'SwiftUI', 'HealthKit', 'UserNotifications'],
    year: '2025',
    role: 'Designer & developer',
    stack: ['Swift', 'SwiftUI', 'SwiftData', 'HealthKit', 'UserNotifications', 'WidgetKit'],
    one: 'A health and medication tracking app that treats users like adults.',
    overview: [
      'I built Optidose after watching a family member juggle five different prescriptions across three reminder apps. The market is full of clinical-looking trackers that feel like they were designed for a clipboard. This one isn\'t.',
      'Optidose syncs adherence data with HealthKit, schedules contextual reminders that respect Focus modes, and keeps a 30-day adherence ring on the home screen via WidgetKit.',
    ],
    features: [
      { t: 'Adherence rings', d: 'A pair of rings on the home screen tracks weekly + 30-day adherence at a glance, with HealthKit as the source of truth.' },
      { t: 'Contextual reminders', d: 'Notifications respect Focus, Sleep, and Do Not Disturb — and escalate only if a critical dose is missed.' },
      { t: 'Onboarding worth doing', d: 'A guided dosage builder that converts pharmacy labels into structured schedules in under two minutes.' },
      { t: 'Doctor-ready export', d: 'A one-tap PDF summary of the last 90 days, formatted for clinician review.' },
    ],
    metrics: [
      { v: '180', k: 'TestFlight users' },
      { v: '94%', k: 'mean adherence' },
      { v: '12+', k: 'clinician sign-offs' },
    ],
  },
  {
    id: 'sketchy',
    index: '05',
    name: 'Sketchy',
    tagline: 'A party game that fits in your pocket.',
    blurb: 'Drawing, guessing, voting, screaming. A Pictionary-shaped party game built around a phased state machine.',
    status: 'dev',
    statusLabel: 'In development',
    screen: 'ScreenSketchy',
    tint: 'rgba(253, 224, 71, 0.28)',
    tags: ['iOS 17+', 'SwiftUI', 'GameKit', 'PencilKit'],
    year: '2026',
    role: 'Designer & developer',
    stack: ['Swift', 'SwiftUI', 'PencilKit', 'GameKit', 'Combine', 'CloudKit'],
    one: 'A multiplayer drawing/guessing party game with a four-phase round loop.',
    overview: [
      'Sketchy started as a way to stress-test a GameManager pattern I\'d been sketching out. Every round cycles through four discrete phases — draw, discuss, vote, results — with their own UI, sounds and timing.',
      'The drawing surface is built on PencilKit with custom stroke smoothing; the voting and results phases reuse a single timeline component skinned three ways. It runs over GameKit\'s real-time matchmaking, so anyone with the app can host a lobby.',
    ],
    features: [
      { t: 'Four-phase round', d: 'A finite-state machine that cleanly separates draw, discuss, vote, and results — each phase a polished mini-screen.' },
      { t: 'PencilKit canvas', d: 'Custom stroke smoothing, palm rejection, and one-tap colour swap. Works just as well on iPhone as iPad.' },
      { t: 'Real-time matchmaking', d: 'GameKit handles invites, lobbies and reconnections. CloudKit holds room state so latecomers can join mid-round.' },
      { t: 'Hidden-prompt reveal', d: 'A timed unveiling at the end of each round, animated with TimelineView and SF Symbol effects.' },
    ],
    metrics: [
      { v: 'Q3', k: 'target launch' },
      { v: '6', k: 'players per room' },
      { v: '40+', k: 'prompt categories' },
    ],
  },
];

window.APPS_DATA = APPS_DATA;
